apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: purview-classification-drift-notifier
  name: purview-classification-drift-notifier
  namespace: purview
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: purview-classification-drift-notifier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: purview-classification-drift-notifier
    spec:
      containers:
        - image: mdrrakiburrahman/purview-classification-drift-notifier
          imagePullPolicy: Always
          name: purview-classification-drift-notifier
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PURVIEW_NAME
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: PURVIEW_NAME
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: AZURE_TENANT_ID
            - name: EVENT_HUB_NAME
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: EVENT_HUB_NAME
            - name: EVENT_HUB_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: EVENT_HUB_CONN_STR
            - name: AZURE_STORAGE_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: AZURE_STORAGE_CONN_STR
            - name: AZURE_BLOB_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: purview-secret
                  key: AZURE_BLOB_CONTAINER
---
apiVersion: v1
kind: Secret
metadata:
  name: purview-secret
  namespace: purview
type: Opaque
stringData:
  PURVIEW_NAME: "your--purview--account"
  AZURE_CLIENT_ID: "your--client--id"
  AZURE_CLIENT_SECRET: "your--client--secret"
  AZURE_TENANT_ID: "your--tenant"
  EVENT_HUB_NAME: "atlas_entities"
  EVENT_HUB_CONN_STR: "Endpoint=sb://your--purview--eh.servicebus.windows.net/;SharedAccessKeyName=AlternateSharedAccessKey;SharedAccessKey=your--access--key"
  AZURE_STORAGE_CONN_STR: "your--storage--account--connstr"
  AZURE_BLOB_CONTAINER: "your--storage--container"
